//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hanif Sugiyanto @hanifsgy
//

import RxSwift
import RxCocoa


final class ___VARIABLE_productName:identifier___ViewModel: ViewModelType {

    var input: Input
    var output: Output!

    // MARK: - Input
    struct Input {
    
    }
    // MARK: - Output
    struct Output {

    }

    let navigator: ___VARIABLE_productName:identifier___Navigator

    init(navigator: ___VARIABLE_productName:identifier___Navigator) {
        self.navigator = navigator

        input = Input()

        output = Output()
    }

}