//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hanif Sugiyanto @hanifsgy
//

import RxSwift
import RxCocoa
import UIKit


class ___VARIABLE_productName:identifier___ViewController: UIViewController {

    // MARK: - Outlets


    // MARK: - Properties

    private var disposeBag: DisposeBag = DisposeBag()
    var viewModel: ___VARIABLE_productName:identifier___ViewModel!

    override func viewDidLoad() {
        super.viewDidLoad()

    }


}
